// All countries

export const COUNTRIES = [
  {
    id: 1,
    phoneCode: 93,
    countryCode: "AF",
    countryNameEn: "Afghanistan",
    alpha_3: "AFG",
    continentCode: "AS",
    continentNameEn: "Asia",
  },
  {
    id: 2,
    phoneCode: 358,
    countryCode: "AX",
    countryNameEn: "Aland Islands",
    alpha_3: "ALA",
    continentCode: "EU",
    continentNameEn: "Europe",
  },
  {
    id: 3,
    phoneCode: 355,
    countryCode: "AL",
    countryNameEn: "Albania",
    countryNameDe: "Albanien",
    alpha_3: "ALB",
    continentCode: "EU",
    continentNameEn: "Europe",
  },
  {
    id: 4,
    phoneCode: 213,
    countryCode: "DZ",
    countryNameEn: "Algeria",
    alpha_3: "DZA",
    continentCode: "AF",
    continentNameEn: "Africa",
  },
  {
    id: 5,
    phoneCode: 1684,
    countryCode: "AS",
    countryNameEn: "American Samoa",
    alpha_3: "ASM",
    continentCode: "OC",
    continentNameEn: "Oceania",
  },
  {
    id: 6,
    phoneCode: 376,
    countryCode: "AD",
    countryNameEn: "Andorra",
    alpha_3: "AND",
    continentCode: "EU",
    continentNameEn: "Europe",
  },
  {
    id: 7,
    phoneCode: 244,
    countryCode: "AO",
    countryNameEn: "Angola",
    alpha_3: "AGO",
    continentCode: "AF",
    continentNameEn: "Africa",
  },
  {
    id: 8,
    phoneCode: 1264,
    countryCode: "AI",
    countryNameEn: "Anguilla",
    alpha_3: "AIA",
    continentCode: "NA",
    continentNameEn: "North America",
  },
  {
    id: 9,
    phoneCode: 672,
    countryCode: "AQ",
    countryNameEn: "Antarctica",
    alpha_3: "ATA",
    continentCode: "AN",
    continentNameEn: "Antarctica",
  },
  {
    id: 10,
    phoneCode: 1268,
    countryCode: "AG",
    countryNameEn: "Antigua and Barbuda",
    alpha_3: "ATG",
    continentCode: "NA",
    continentNameEn: "North America",
  },
  {
    id: 11,
    phoneCode: 54,
    countryCode: "AR",
    countryNameEn: "Argentina",
    alpha_3: "ARG",
    continentCode: "SA",
    continentNameEn: "South America",
  },
  {
    id: 12,
    phoneCode: 374,
    countryCode: "AM",
    countryNameEn: "Armenia",
    alpha_3: "ARM",
    continentCode: "AS",
    continentNameEn: "Asia",
  },
  {
    id: 13,
    phoneCode: 297,
    countryCode: "AW",
    countryNameEn: "Aruba",
    alpha_3: "ABW",
    continentCode: "NA",
    continentNameEn: "North America",
  },
  {
    id: 14,
    phoneCode: 61,
    countryCode: "AU",
    countryNameEn: "Australia",
    alpha_3: "AUS",
    continentCode: "OC",
    continentNameEn: "Oceania",
  },
  {
    id: 15,
    phoneCode: 43,
    countryCode: "AT",
    countryNameEn: "Austria",
    countryNameDe: "Österreich",
    alpha_3: "AUT",
    continentCode: "EU",
    continentNameEn: "Europe",
  },
  {
    id: 16,
    phoneCode: 994,
    countryCode: "AZ",
    countryNameEn: "Azerbaijan",
    alpha_3: "AZE",
    continentCode: "AS",
    continentNameEn: "Asia",
  },
  {
    id: 17,
    phoneCode: 1242,
    countryCode: "BS",
    countryNameEn: "Bahamas",
    alpha_3: "BHS",
    continentCode: "NA",
    continentNameEn: "North America",
  },
  {
    id: 18,
    phoneCode: 973,
    countryCode: "BH",
    countryNameEn: "Bahrain",
    alpha_3: "BHR",
    continentCode: "AS",
    continentNameEn: "Asia",
  },
  {
    id: 19,
    phoneCode: 880,
    countryCode: "BD",
    countryNameEn: "Bangladesh",
    alpha_3: "BGD",
    continentCode: "AS",
    continentNameEn: "Asia",
  },
  {
    id: 20,
    phoneCode: 1246,
    countryCode: "BB",
    countryNameEn: "Barbados",
    alpha_3: "BRB",
    continentCode: "NA",
    continentNameEn: "North America",
  },
  {
    id: 21,
    phoneCode: 375,
    countryCode: "BY",
    countryNameEn: "Belarus",
    alpha_3: "BLR",
    continentCode: "EU",
    continentNameEn: "Europe",
  },
  {
    id: 22,
    phoneCode: 32,
    countryCode: "BE",
    countryNameEn: "Belgium",
    alpha_3: "BEL",
    continentCode: "EU",
    continentNameEn: "Europe",
  },
  {
    id: 23,
    phoneCode: 501,
    countryCode: "BZ",
    countryNameEn: "Belize",
    alpha_3: "BLZ",
    continentCode: "NA",
    continentNameEn: "North America",
  },
  {
    id: 24,
    phoneCode: 229,
    countryCode: "BJ",
    countryNameEn: "Benin",
    alpha_3: "BEN",
    continentCode: "AF",
    continentNameEn: "Africa",
  },
  {
    id: 25,
    phoneCode: 1441,
    countryCode: "BM",
    countryNameEn: "Bermuda",
    alpha_3: "BMU",
    continentCode: "NA",
    continentNameEn: "North America",
  },
  {
    id: 26,
    phoneCode: 975,
    countryCode: "BT",
    countryNameEn: "Bhutan",
    alpha_3: "BTN",
    continentCode: "AS",
    continentNameEn: "Asia",
  },
  {
    id: 27,
    phoneCode: 591,
    countryCode: "BO",
    countryNameEn: "Bolivia",
    alpha_3: "BOL",
    continentCode: "SA",
    continentNameEn: "South America",
  },
  {
    id: 28,
    phoneCode: 599,
    countryCode: "BQ",
    countryNameEn: "Bonaire, Sint Eustatius and Saba",
    alpha_3: "BES",
    continentCode: "NA",
    continentNameEn: "North America",
  },
  {
    id: 29,
    phoneCode: 387,
    countryCode: "BA",
    countryNameEn: "Bosnia and Herzegovina",
    alpha_3: "BIH",
    continentCode: "EU",
    continentNameEn: "Europe",
  },
  {
    id: 30,
    phoneCode: 267,
    countryCode: "BW",
    countryNameEn: "Botswana",
    alpha_3: "BWA",
    continentCode: "AF",
    continentNameEn: "Africa",
  },
  {
    id: 31,
    phoneCode: 55,
    countryCode: "BV",
    countryNameEn: "Bouvet Island",
    alpha_3: "BVT",
    continentCode: "AN",
    continentNameEn: "Antarctica",
  },
  {
    id: 32,
    phoneCode: 55,
    countryCode: "BR",
    countryNameEn: "Brazil",
    alpha_3: "BRA",
    continentCode: "SA",
    continentNameEn: "South America",
  },
  {
    id: 33,
    phoneCode: 246,
    countryCode: "IO",
    countryNameEn: "British Indian Ocean Territory",
    alpha_3: "IOT",
    continentCode: "AS",
    continentNameEn: "Asia",
  },
  {
    id: 34,
    phoneCode: 673,
    countryCode: "BN",
    countryNameEn: "Brunei Darussalam",
    alpha_3: "BRN",
    continentCode: "AS",
    continentNameEn: "Asia",
  },
  {
    id: 35,
    phoneCode: 359,
    countryCode: "BG",
    countryNameEn: "Bulgaria",
    alpha_3: "BGR",
    continentCode: "EU",
    continentNameEn: "Europe",
  },
  {
    id: 36,
    phoneCode: 226,
    countryCode: "BF",
    countryNameEn: "Burkina Faso",
    alpha_3: "BFA",
    continentCode: "AF",
    continentNameEn: "Africa",
  },
  {
    id: 37,
    phoneCode: 257,
    countryCode: "BI",
    countryNameEn: "Burundi",
    alpha_3: "BDI",
    continentCode: "AF",
    continentNameEn: "Africa",
  },
  {
    id: 38,
    phoneCode: 855,
    countryCode: "KH",
    countryNameEn: "Cambodia",
    alpha_3: "KHM",
    continentCode: "AS",
    continentNameEn: "Asia",
  },
  {
    id: 39,
    phoneCode: 237,
    countryCode: "CM",
    countryNameEn: "Cameroon",
    alpha_3: "CMR",
    continentCode: "AF",
    continentNameEn: "Africa",
  },
  {
    id: 40,
    phoneCode: 1,
    countryCode: "CA",
    countryNameEn: "Canada",
    alpha_3: "CAN",
    continentCode: "NA",
    continentNameEn: "North America",
  },
  {
    id: 41,
    phoneCode: 238,
    countryCode: "CV",
    countryNameEn: "Cape Verde",
    alpha_3: "CPV",
    continentCode: "AF",
    continentNameEn: "Africa",
  },
  {
    id: 42,
    phoneCode: 1345,
    countryCode: "KY",
    countryNameEn: "Cayman Islands",
    alpha_3: "CYM",
    continentCode: "NA",
    continentNameEn: "North America",
  },
  {
    id: 43,
    phoneCode: 236,
    countryCode: "CF",
    countryNameEn: "Central African Republic",
    alpha_3: "CAF",
    continentCode: "AF",
    continentNameEn: "Africa",
  },
  {
    id: 44,
    phoneCode: 235,
    countryCode: "TD",
    countryNameEn: "Chad",
    alpha_3: "TCD",
    continentCode: "AF",
    continentNameEn: "Africa",
  },
  {
    id: 45,
    phoneCode: 56,
    countryCode: "CL",
    countryNameEn: "Chile",
    alpha_3: "CHL",
    continentCode: "SA",
    continentNameEn: "South America",
  },
  {
    id: 46,
    phoneCode: 86,
    countryCode: "CN",
    countryNameEn: "China",
    alpha_3: "CHN",
    continentCode: "AS",
    continentNameEn: "Asia",
  },
  {
    id: 47,
    phoneCode: 61,
    countryCode: "CX",
    countryNameEn: "Christmas Island",
    alpha_3: "CXR",
    continentCode: "AS",
    continentNameEn: "Asia",
  },
  {
    id: 48,
    phoneCode: 672,
    countryCode: "CC",
    countryNameEn: "Cocos (Keeling) Islands",
    alpha_3: "CCK",
    continentCode: "AS",
    continentNameEn: "Asia",
  },
  {
    id: 49,
    phoneCode: 57,
    countryCode: "CO",
    countryNameEn: "Colombia",
    alpha_3: "COL",
    continentCode: "SA",
    continentNameEn: "South America",
  },
  {
    id: 50,
    phoneCode: 269,
    countryCode: "KM",
    countryNameEn: "Comoros",
    alpha_3: "COM",
    continentCode: "AF",
    continentNameEn: "Africa",
  },
  {
    id: 51,
    phoneCode: 242,
    countryCode: "CG",
    countryNameEn: "Congo",
    alpha_3: "COG",
    continentCode: "AF",
    continentNameEn: "Africa",
  },
  {
    id: 52,
    phoneCode: 242,
    countryCode: "CD",
    countryNameEn: "Congo, Democratic Republic of the Congo",
    alpha_3: "COD",
    continentCode: "AF",
    continentNameEn: "Africa",
  },
  {
    id: 53,
    phoneCode: 682,
    countryCode: "CK",
    countryNameEn: "Cook Islands",
    alpha_3: "COK",
    continentCode: "OC",
    continentNameEn: "Oceania",
  },
  {
    id: 54,
    phoneCode: 506,
    countryCode: "CR",
    countryNameEn: "Costa Rica",
    alpha_3: "CRI",
    continentCode: "NA",
    continentNameEn: "North America",
  },
  {
    id: 55,
    phoneCode: 225,
    countryCode: "CI",
    countryNameEn: "Cote D'Ivoire",
    alpha_3: "CIV",
    continentCode: "AF",
    continentNameEn: "Africa",
  },
  {
    id: 56,
    phoneCode: 385,
    countryCode: "HR",
    countryNameEn: "Croatia",
    alpha_3: "HRV",
    continentCode: "EU",
    continentNameEn: "Europe",
  },
  {
    id: 57,
    phoneCode: 53,
    countryCode: "CU",
    countryNameEn: "Cuba",
    alpha_3: "CUB",
    continentCode: "NA",
    continentNameEn: "North America",
  },
  {
    id: 58,
    phoneCode: 599,
    countryCode: "CW",
    countryNameEn: "Curacao",
    alpha_3: "CUW",
    continentCode: "NA",
    continentNameEn: "North America",
  },
  {
    id: 59,
    phoneCode: 357,
    countryCode: "CY",
    countryNameEn: "Cyprus",
    alpha_3: "CYP",
    continentCode: "AS",
    continentNameEn: "Asia",
  },
  {
    id: 60,
    phoneCode: 420,
    countryCode: "CZ",
    countryNameEn: "Czech Republic",
    alpha_3: "CZE",
    continentCode: "EU",
    continentNameEn: "Europe",
  },
  {
    id: 61,
    phoneCode: 45,
    countryCode: "DK",
    countryNameEn: "Denmark",
    countryNameDe: "Dänemark",
    alpha_3: "DNK",
    continentCode: "EU",
    continentNameEn: "Europe",
  },
  {
    id: 62,
    phoneCode: 253,
    countryCode: "DJ",
    countryNameEn: "Djibouti",
    alpha_3: "DJI",
    continentCode: "AF",
    continentNameEn: "Africa",
  },
  {
    id: 63,
    phoneCode: 1767,
    countryCode: "DM",
    countryNameEn: "Dominica",
    alpha_3: "DMA",
    continentCode: "NA",
    continentNameEn: "North America",
  },
  {
    id: 64,
    phoneCode: 1809,
    countryCode: "DO",
    countryNameEn: "Dominican Republic",
    alpha_3: "DOM",
    continentCode: "NA",
    continentNameEn: "North America",
  },
  {
    id: 65,
    phoneCode: 593,
    countryCode: "EC",
    countryNameEn: "Ecuador",
    alpha_3: "ECU",
    continentCode: "SA",
    continentNameEn: "South America",
  },
  {
    id: 66,
    phoneCode: 20,
    countryCode: "EG",
    countryNameEn: "Egypt",
    alpha_3: "EGY",
    continentCode: "AF",
    continentNameEn: "Africa",
  },
  {
    id: 67,
    phoneCode: 503,
    countryCode: "SV",
    countryNameEn: "El Salvador",
    alpha_3: "SLV",
    continentCode: "NA",
    continentNameEn: "North America",
  },
  {
    id: 68,
    phoneCode: 240,
    countryCode: "GQ",
    countryNameEn: "Equatorial Guinea",
    alpha_3: "GNQ",
    continentCode: "AF",
    continentNameEn: "Africa",
  },
  {
    id: 69,
    phoneCode: 291,
    countryCode: "ER",
    countryNameEn: "Eritrea",
    alpha_3: "ERI",
    continentCode: "AF",
    continentNameEn: "Africa",
  },
  {
    id: 70,
    phoneCode: 372,
    countryCode: "EE",
    countryNameEn: "Estonia",
    alpha_3: "EST",
    continentCode: "EU",
    continentNameEn: "Europe",
  },
  {
    id: 71,
    phoneCode: 251,
    countryCode: "ET",
    countryNameEn: "Ethiopia",
    alpha_3: "ETH",
    continentCode: "AF",
    continentNameEn: "Africa",
  },
  {
    id: 72,
    phoneCode: 500,
    countryCode: "FK",
    countryNameEn: "Falkland Islands (Malvinas)",
    alpha_3: "FLK",
    continentCode: "SA",
    continentNameEn: "South America",
  },
  {
    id: 73,
    phoneCode: 298,
    countryCode: "FO",
    countryNameEn: "Faroe Islands",
    alpha_3: "FRO",
    continentCode: "EU",
    continentNameEn: "Europe",
  },
  {
    id: 74,
    phoneCode: 679,
    countryCode: "FJ",
    countryNameEn: "Fiji",
    alpha_3: "FJI",
    continentCode: "OC",
    continentNameEn: "Oceania",
  },
  {
    id: 75,
    phoneCode: 358,
    countryCode: "FI",
    countryNameEn: "Finland",
    alpha_3: "FIN",
    continentCode: "EU",
    continentNameEn: "Europe",
  },
  {
    id: 76,
    phoneCode: 33,
    countryCode: "FR",
    countryNameEn: "France",
    alpha_3: "FRA",
    continentCode: "EU",
    continentNameEn: "Europe",
  },
  {
    id: 77,
    phoneCode: 594,
    countryCode: "GF",
    countryNameEn: "French Guiana",
    alpha_3: "GUF",
    continentCode: "SA",
    continentNameEn: "South America",
  },
  {
    id: 78,
    phoneCode: 689,
    countryCode: "PF",
    countryNameEn: "French Polynesia",
    alpha_3: "PYF",
    continentCode: "OC",
    continentNameEn: "Oceania",
  },
  {
    id: 79,
    phoneCode: 262,
    countryCode: "TF",
    countryNameEn: "French Southern Territories",
    alpha_3: "ATF",
    continentCode: "AN",
    continentNameEn: "Antarctica",
  },
  {
    id: 80,
    phoneCode: 241,
    countryCode: "GA",
    countryNameEn: "Gabon",
    alpha_3: "GAB",
    continentCode: "AF",
    continentNameEn: "Africa",
  },
  {
    id: 81,
    phoneCode: 220,
    countryCode: "GM",
    countryNameEn: "Gambia",
    alpha_3: "GMB",
    continentCode: "AF",
    continentNameEn: "Africa",
  },
  {
    id: 82,
    phoneCode: 995,
    countryCode: "GE",
    countryNameEn: "Georgia",
    alpha_3: "GEO",
    continentCode: "AS",
    continentNameEn: "Asia",
  },
  {
    id: 83,
    phoneCode: 49,
    countryCode: "DE",
    countryNameEn: "Germany",
    countryNameDe: "Deutschland",
    alpha_3: "DEU",
    continentCode: "EU",
    continentNameEn: "Europe",
  },
  {
    id: 84,
    phoneCode: 233,
    countryCode: "GH",
    countryNameEn: "Ghana",
    alpha_3: "GHA",
    continentCode: "AF",
    continentNameEn: "Africa",
  },
  {
    id: 85,
    phoneCode: 350,
    countryCode: "GI",
    countryNameEn: "Gibraltar",
    alpha_3: "GIB",
    continentCode: "EU",
    continentNameEn: "Europe",
  },
  {
    id: 86,
    phoneCode: 30,
    countryCode: "GR",
    countryNameEn: "Greece",
    alpha_3: "GRC",
    continentCode: "EU",
    continentNameEn: "Europe",
  },
  {
    id: 87,
    phoneCode: 299,
    countryCode: "GL",
    countryNameEn: "Greenland",
    alpha_3: "GRL",
    continentCode: "NA",
    continentNameEn: "North America",
  },
  {
    id: 88,
    phoneCode: 1473,
    countryCode: "GD",
    countryNameEn: "Grenada",
    alpha_3: "GRD",
    continentCode: "NA",
    continentNameEn: "North America",
  },
  {
    id: 89,
    phoneCode: 590,
    countryCode: "GP",
    countryNameEn: "Guadeloupe",
    alpha_3: "GLP",
    continentCode: "NA",
    continentNameEn: "North America",
  },
  {
    id: 90,
    phoneCode: 1671,
    countryCode: "GU",
    countryNameEn: "Guam",
    alpha_3: "GUM",
    continentCode: "OC",
    continentNameEn: "Oceania",
  },
  {
    id: 91,
    phoneCode: 502,
    countryCode: "GT",
    countryNameEn: "Guatemala",
    alpha_3: "GTM",
    continentCode: "NA",
    continentNameEn: "North America",
  },
  {
    id: 92,
    phoneCode: 44,
    countryCode: "GG",
    countryNameEn: "Guernsey",
    alpha_3: "GGY",
    continentCode: "EU",
    continentNameEn: "Europe",
  },
  {
    id: 93,
    phoneCode: 224,
    countryCode: "GN",
    countryNameEn: "Guinea",
    alpha_3: "GIN",
    continentCode: "AF",
    continentNameEn: "Africa",
  },
  {
    id: 94,
    phoneCode: 245,
    countryCode: "GW",
    countryNameEn: "Guinea-Bissau",
    alpha_3: "GNB",
    continentCode: "AF",
    continentNameEn: "Africa",
  },
  {
    id: 95,
    phoneCode: 592,
    countryCode: "GY",
    countryNameEn: "Guyana",
    alpha_3: "GUY",
    continentCode: "SA",
    continentNameEn: "South America",
  },
  {
    id: 96,
    phoneCode: 509,
    countryCode: "HT",
    countryNameEn: "Haiti",
    alpha_3: "HTI",
    continentCode: "NA",
    continentNameEn: "North America",
  },
  {
    id: 97,
    phoneCode: 0,
    countryCode: "HM",
    countryNameEn: "Heard Island and Mcdonald Islands",
    alpha_3: "HMD",
    continentCode: "AN",
    continentNameEn: "Antarctica",
  },
  {
    id: 98,
    phoneCode: 39,
    countryCode: "VA",
    countryNameEn: "Holy See (Vatican City State)",
    alpha_3: "VAT",
    continentCode: "EU",
    continentNameEn: "Europe",
  },
  {
    id: 99,
    phoneCode: 504,
    countryCode: "HN",
    countryNameEn: "Honduras",
    alpha_3: "HND",
    continentCode: "NA",
    continentNameEn: "North America",
  },
  {
    id: 100,
    phoneCode: 852,
    countryCode: "HK",
    countryNameEn: "Hong Kong",
    alpha_3: "HKG",
    continentCode: "AS",
    continentNameEn: "Asia",
  },
  {
    id: 101,
    phoneCode: 36,
    countryCode: "HU",
    countryNameEn: "Hungary",
    alpha_3: "HUN",
    continentCode: "EU",
    continentNameEn: "Europe",
  },
  {
    id: 102,
    phoneCode: 354,
    countryCode: "IS",
    countryNameEn: "Iceland",
    alpha_3: "ISL",
    continentCode: "EU",
    continentNameEn: "Europe",
  },
  {
    id: 103,
    phoneCode: 91,
    countryCode: "IN",
    countryNameEn: "India",
    alpha_3: "IND",
    continentCode: "AS",
    continentNameEn: "Asia",
  },
  {
    id: 104,
    phoneCode: 62,
    countryCode: "ID",
    countryNameEn: "Indonesia",
    alpha_3: "IDN",
    continentCode: "AS",
    continentNameEn: "Asia",
  },
  {
    id: 105,
    phoneCode: 98,
    countryCode: "IR",
    countryNameEn: "Iran, Islamic Republic of",
    alpha_3: "IRN",
    continentCode: "AS",
    continentNameEn: "Asia",
  },
  {
    id: 106,
    phoneCode: 964,
    countryCode: "IQ",
    countryNameEn: "Iraq",
    alpha_3: "IRQ",
    continentCode: "AS",
    continentNameEn: "Asia",
  },
  {
    id: 107,
    phoneCode: 353,
    countryCode: "IE",
    countryNameEn: "Ireland",
    alpha_3: "IRL",
    continentCode: "EU",
    continentNameEn: "Europe",
  },
  {
    id: 108,
    phoneCode: 44,
    countryCode: "IM",
    countryNameEn: "Isle of Man",
    alpha_3: "IMN",
    continentCode: "EU",
    continentNameEn: "Europe",
  },
  {
    id: 109,
    phoneCode: 972,
    countryCode: "IL",
    countryNameEn: "Israel",
    alpha_3: "ISR",
    continentCode: "AS",
    continentNameEn: "Asia",
  },
  {
    id: 110,
    phoneCode: 39,
    countryCode: "IT",
    countryNameEn: "Italy",
    alpha_3: "ITA",
    continentCode: "EU",
    continentNameEn: "Europe",
  },
  {
    id: 111,
    phoneCode: 1876,
    countryCode: "JM",
    countryNameEn: "Jamaica",
    alpha_3: "JAM",
    continentCode: "NA",
    continentNameEn: "North America",
  },
  {
    id: 112,
    phoneCode: 81,
    countryCode: "JP",
    countryNameEn: "Japan",
    alpha_3: "JPN",
    continentCode: "AS",
    continentNameEn: "Asia",
  },
  {
    id: 113,
    phoneCode: 44,
    countryCode: "JE",
    countryNameEn: "Jersey",
    alpha_3: "JEY",
    continentCode: "EU",
    continentNameEn: "Europe",
  },
  {
    id: 114,
    phoneCode: 962,
    countryCode: "JO",
    countryNameEn: "Jordan",
    alpha_3: "JOR",
    continentCode: "AS",
    continentNameEn: "Asia",
  },
  {
    id: 115,
    phoneCode: 7,
    countryCode: "KZ",
    countryNameEn: "Kazakhstan",
    alpha_3: "KAZ",
    continentCode: "AS",
    continentNameEn: "Asia",
  },
  {
    id: 116,
    phoneCode: 254,
    countryCode: "KE",
    countryNameEn: "Kenya",
    alpha_3: "KEN",
    continentCode: "AF",
    continentNameEn: "Africa",
  },
  {
    id: 117,
    phoneCode: 686,
    countryCode: "KI",
    countryNameEn: "Kiribati",
    alpha_3: "KIR",
    continentCode: "OC",
    continentNameEn: "Oceania",
  },
  {
    id: 118,
    phoneCode: 850,
    countryCode: "KP",
    countryNameEn: "Korea, Democratic People's Republic of",
    alpha_3: "PRK",
    continentCode: "AS",
    continentNameEn: "Asia",
  },
  {
    id: 119,
    phoneCode: 82,
    countryCode: "KR",
    countryNameEn: "Korea, Republic of",
    alpha_3: "KOR",
    continentCode: "AS",
    continentNameEn: "Asia",
  },
  {
    id: 120,
    phoneCode: 381,
    countryCode: "XK",
    countryNameEn: "Kosovo",
    alpha_3: "XKX",
    continentCode: "EU",
    continentNameEn: "Europe",
  },
  {
    id: 121,
    phoneCode: 965,
    countryCode: "KW",
    countryNameEn: "Kuwait",
    alpha_3: "KWT",
    continentCode: "AS",
    continentNameEn: "Asia",
  },
  {
    id: 122,
    phoneCode: 996,
    countryCode: "KG",
    countryNameEn: "Kyrgyzstan",
    alpha_3: "KGZ",
    continentCode: "AS",
    continentNameEn: "Asia",
  },
  {
    id: 123,
    phoneCode: 856,
    countryCode: "LA",
    countryNameEn: "Lao People's Democratic Republic",
    alpha_3: "LAO",
    continentCode: "AS",
    continentNameEn: "Asia",
  },
  {
    id: 124,
    phoneCode: 371,
    countryCode: "LV",
    countryNameEn: "Latvia",
    alpha_3: "LVA",
    continentCode: "EU",
    continentNameEn: "Europe",
  },
  {
    id: 125,
    phoneCode: 961,
    countryCode: "LB",
    countryNameEn: "Lebanon",
    alpha_3: "LBN",
    continentCode: "AS",
    continentNameEn: "Asia",
  },
  {
    id: 126,
    phoneCode: 266,
    countryCode: "LS",
    countryNameEn: "Lesotho",
    alpha_3: "LSO",
    continentCode: "AF",
    continentNameEn: "Africa",
  },
  {
    id: 127,
    phoneCode: 231,
    countryCode: "LR",
    countryNameEn: "Liberia",
    alpha_3: "LBR",
    continentCode: "AF",
    continentNameEn: "Africa",
  },
  {
    id: 128,
    phoneCode: 218,
    countryCode: "LY",
    countryNameEn: "Libyan Arab Jamahiriya",
    alpha_3: "LBY",
    continentCode: "AF",
    continentNameEn: "Africa",
  },
  {
    id: 129,
    phoneCode: 423,
    countryCode: "LI",
    countryNameEn: "Liechtenstein",
    alpha_3: "LIE",
    continentCode: "EU",
    continentNameEn: "Europe",
  },
  {
    id: 130,
    phoneCode: 370,
    countryCode: "LT",
    countryNameEn: "Lithuania",
    alpha_3: "LTU",
    continentCode: "EU",
    continentNameEn: "Europe",
  },
  {
    id: 131,
    phoneCode: 352,
    countryCode: "LU",
    countryNameEn: "Luxembourg",
    alpha_3: "LUX",
    continentCode: "EU",
    continentNameEn: "Europe",
  },
  {
    id: 132,
    phoneCode: 853,
    countryCode: "MO",
    countryNameEn: "Macao",
    alpha_3: "MAC",
    continentCode: "AS",
    continentNameEn: "Asia",
  },
  {
    id: 133,
    phoneCode: 389,
    countryCode: "MK",
    countryNameEn: "Macedonia, the Former Yugoslav Republic of",
    alpha_3: "MKD",
    continentCode: "EU",
    continentNameEn: "Europe",
  },
  {
    id: 134,
    phoneCode: 261,
    countryCode: "MG",
    countryNameEn: "Madagascar",
    alpha_3: "MDG",
    continentCode: "AF",
    continentNameEn: "Africa",
  },
  {
    id: 135,
    phoneCode: 265,
    countryCode: "MW",
    countryNameEn: "Malawi",
    alpha_3: "MWI",
    continentCode: "AF",
    continentNameEn: "Africa",
  },
  {
    id: 136,
    phoneCode: 60,
    countryCode: "MY",
    countryNameEn: "Malaysia",
    alpha_3: "MYS",
    continentCode: "AS",
    continentNameEn: "Asia",
  },
  {
    id: 137,
    phoneCode: 960,
    countryCode: "MV",
    countryNameEn: "Maldives",
    alpha_3: "MDV",
    continentCode: "AS",
    continentNameEn: "Asia",
  },
  {
    id: 138,
    phoneCode: 223,
    countryCode: "ML",
    countryNameEn: "Mali",
    alpha_3: "MLI",
    continentCode: "AF",
    continentNameEn: "Africa",
  },
  {
    id: 139,
    phoneCode: 356,
    countryCode: "MT",
    countryNameEn: "Malta",
    alpha_3: "MLT",
    continentCode: "EU",
    continentNameEn: "Europe",
  },
  {
    id: 140,
    phoneCode: 692,
    countryCode: "MH",
    countryNameEn: "Marshall Islands",
    alpha_3: "MHL",
    continentCode: "OC",
    continentNameEn: "Oceania",
  },
  {
    id: 141,
    phoneCode: 596,
    countryCode: "MQ",
    countryNameEn: "Martinique",
    alpha_3: "MTQ",
    continentCode: "NA",
    continentNameEn: "North America",
  },
  {
    id: 142,
    phoneCode: 222,
    countryCode: "MR",
    countryNameEn: "Mauritania",
    alpha_3: "MRT",
    continentCode: "AF",
    continentNameEn: "Africa",
  },
  {
    id: 143,
    phoneCode: 230,
    countryCode: "MU",
    countryNameEn: "Mauritius",
    alpha_3: "MUS",
    continentCode: "AF",
    continentNameEn: "Africa",
  },
  {
    id: 144,
    phoneCode: 269,
    countryCode: "YT",
    countryNameEn: "Mayotte",
    alpha_3: "MYT",
    continentCode: "AF",
    continentNameEn: "Africa",
  },
  {
    id: 145,
    phoneCode: 52,
    countryCode: "MX",
    countryNameEn: "Mexico",
    alpha_3: "MEX",
    continentCode: "NA",
    continentNameEn: "North America",
  },
  {
    id: 146,
    phoneCode: 691,
    countryCode: "FM",
    countryNameEn: "Micronesia, Federated States of",
    alpha_3: "FSM",
    continentCode: "OC",
    continentNameEn: "Oceania",
  },
  {
    id: 147,
    phoneCode: 373,
    countryCode: "MD",
    countryNameEn: "Moldova, Republic of",
    alpha_3: "MDA",
    continentCode: "EU",
    continentNameEn: "Europe",
  },
  {
    id: 148,
    phoneCode: 377,
    countryCode: "MC",
    countryNameEn: "Monaco",
    alpha_3: "MCO",
    continentCode: "EU",
    continentNameEn: "Europe",
  },
  {
    id: 149,
    phoneCode: 976,
    countryCode: "MN",
    countryNameEn: "Mongolia",
    alpha_3: "MNG",
    continentCode: "AS",
    continentNameEn: "Asia",
  },
  {
    id: 150,
    phoneCode: 382,
    countryCode: "ME",
    countryNameEn: "Montenegro",
    alpha_3: "MNE",
    continentCode: "EU",
    continentNameEn: "Europe",
  },
  {
    id: 151,
    phoneCode: 1664,
    countryCode: "MS",
    countryNameEn: "Montserrat",
    alpha_3: "MSR",
    continentCode: "NA",
    continentNameEn: "North America",
  },
  {
    id: 152,
    phoneCode: 212,
    countryCode: "MA",
    countryNameEn: "Morocco",
    alpha_3: "MAR",
    continentCode: "AF",
    continentNameEn: "Africa",
  },
  {
    id: 153,
    phoneCode: 258,
    countryCode: "MZ",
    countryNameEn: "Mozambique",
    alpha_3: "MOZ",
    continentCode: "AF",
    continentNameEn: "Africa",
  },
  {
    id: 154,
    phoneCode: 95,
    countryCode: "MM",
    countryNameEn: "Myanmar",
    alpha_3: "MMR",
    continentCode: "AS",
    continentNameEn: "Asia",
  },
  {
    id: 155,
    phoneCode: 264,
    countryCode: "NA",
    countryNameEn: "Namibia",
    alpha_3: "NAM",
    continentCode: "AF",
    continentNameEn: "Africa",
  },
  {
    id: 156,
    phoneCode: 674,
    countryCode: "NR",
    countryNameEn: "Nauru",
    alpha_3: "NRU",
    continentCode: "OC",
    continentNameEn: "Oceania",
  },
  {
    id: 157,
    phoneCode: 977,
    countryCode: "NP",
    countryNameEn: "Nepal",
    alpha_3: "NPL",
    continentCode: "AS",
    continentNameEn: "Asia",
  },
  {
    id: 158,
    phoneCode: 31,
    countryCode: "NL",
    countryNameEn: "Netherlands",
    alpha_3: "NLD",
    continentCode: "EU",
    continentNameEn: "Europe",
  },
  {
    id: 159,
    phoneCode: 599,
    countryCode: "AN",
    countryNameEn: "Netherlands Antilles",
    alpha_3: "ANT",
    continentCode: "NA",
    continentNameEn: "North America",
  },
  {
    id: 160,
    phoneCode: 687,
    countryCode: "NC",
    countryNameEn: "New Caledonia",
    alpha_3: "NCL",
    continentCode: "OC",
    continentNameEn: "Oceania",
  },
  {
    id: 161,
    phoneCode: 64,
    countryCode: "NZ",
    countryNameEn: "New Zealand",
    alpha_3: "NZL",
    continentCode: "OC",
    continentNameEn: "Oceania",
  },
  {
    id: 162,
    phoneCode: 505,
    countryCode: "NI",
    countryNameEn: "Nicaragua",
    alpha_3: "NIC",
    continentCode: "NA",
    continentNameEn: "North America",
  },
  {
    id: 163,
    phoneCode: 227,
    countryCode: "NE",
    countryNameEn: "Niger",
    alpha_3: "NER",
    continentCode: "AF",
    continentNameEn: "Africa",
  },
  {
    id: 164,
    phoneCode: 234,
    countryCode: "NG",
    countryNameEn: "Nigeria",
    alpha_3: "NGA",
    continentCode: "AF",
    continentNameEn: "Africa",
  },
  {
    id: 165,
    phoneCode: 683,
    countryCode: "NU",
    countryNameEn: "Niue",
    alpha_3: "NIU",
    continentCode: "OC",
    continentNameEn: "Oceania",
  },
  {
    id: 166,
    phoneCode: 672,
    countryCode: "NF",
    countryNameEn: "Norfolk Island",
    alpha_3: "NFK",
    continentCode: "OC",
    continentNameEn: "Oceania",
  },
  {
    id: 167,
    phoneCode: 1670,
    countryCode: "MP",
    countryNameEn: "Northern Mariana Islands",
    alpha_3: "MNP",
    continentCode: "OC",
    continentNameEn: "Oceania",
  },
  {
    id: 168,
    phoneCode: 47,
    countryCode: "NO",
    countryNameEn: "Norway",
    alpha_3: "NOR",
    continentCode: "EU",
    continentNameEn: "Europe",
  },
  {
    id: 169,
    phoneCode: 968,
    countryCode: "OM",
    countryNameEn: "Oman",
    alpha_3: "OMN",
    continentCode: "AS",
    continentNameEn: "Asia",
  },
  {
    id: 170,
    phoneCode: 92,
    countryCode: "PK",
    countryNameEn: "Pakistan",
    alpha_3: "PAK",
    continentCode: "AS",
    continentNameEn: "Asia",
  },
  {
    id: 171,
    phoneCode: 680,
    countryCode: "PW",
    countryNameEn: "Palau",
    alpha_3: "PLW",
    continentCode: "OC",
    continentNameEn: "Oceania",
  },
  {
    id: 172,
    phoneCode: 970,
    countryCode: "PS",
    countryNameEn: "Palestinian Territory, Occupied",
    alpha_3: "PSE",
    continentCode: "AS",
    continentNameEn: "Asia",
  },
  {
    id: 173,
    phoneCode: 507,
    countryCode: "PA",
    countryNameEn: "Panama",
    alpha_3: "PAN",
    continentCode: "NA",
    continentNameEn: "North America",
  },
  {
    id: 174,
    phoneCode: 675,
    countryCode: "PG",
    countryNameEn: "Papua New Guinea",
    alpha_3: "PNG",
    continentCode: "OC",
    continentNameEn: "Oceania",
  },
  {
    id: 175,
    phoneCode: 595,
    countryCode: "PY",
    countryNameEn: "Paraguay",
    alpha_3: "PRY",
    continentCode: "SA",
    continentNameEn: "South America",
  },
  {
    id: 176,
    phoneCode: 51,
    countryCode: "PE",
    countryNameEn: "Peru",
    alpha_3: "PER",
    continentCode: "SA",
    continentNameEn: "South America",
  },
  {
    id: 177,
    phoneCode: 63,
    countryCode: "PH",
    countryNameEn: "Philippines",
    alpha_3: "PHL",
    continentCode: "AS",
    continentNameEn: "Asia",
  },
  {
    id: 178,
    phoneCode: 64,
    countryCode: "PN",
    countryNameEn: "Pitcairn",
    alpha_3: "PCN",
    continentCode: "OC",
    continentNameEn: "Oceania",
  },
  {
    id: 179,
    phoneCode: 48,
    countryCode: "PL",
    countryNameEn: "Poland",
    alpha_3: "POL",
    continentCode: "EU",
    continentNameEn: "Europe",
  },
  {
    id: 180,
    phoneCode: 351,
    countryCode: "PT",
    countryNameEn: "Portugal",
    alpha_3: "PRT",
    continentCode: "EU",
    continentNameEn: "Europe",
  },
  {
    id: 181,
    phoneCode: 1787,
    countryCode: "PR",
    countryNameEn: "Puerto Rico",
    alpha_3: "PRI",
    continentCode: "NA",
    continentNameEn: "North America",
  },
  {
    id: 182,
    phoneCode: 974,
    countryCode: "QA",
    countryNameEn: "Qatar",
    alpha_3: "QAT",
    continentCode: "AS",
    continentNameEn: "Asia",
  },
  {
    id: 183,
    phoneCode: 262,
    countryCode: "RE",
    countryNameEn: "Reunion",
    alpha_3: "REU",
    continentCode: "AF",
    continentNameEn: "Africa",
  },
  {
    id: 184,
    phoneCode: 40,
    countryCode: "RO",
    countryNameEn: "Romania",
    alpha_3: "ROM",
    continentCode: "EU",
    continentNameEn: "Europe",
  },
  {
    id: 185,
    phoneCode: 70,
    countryCode: "RU",
    countryNameEn: "Russian Federation",
    alpha_3: "RUS",
    continentCode: "AS",
    continentNameEn: "Asia",
  },
  {
    id: 186,
    phoneCode: 250,
    countryCode: "RW",
    countryNameEn: "Rwanda",
    alpha_3: "RWA",
    continentCode: "AF",
    continentNameEn: "Africa",
  },
  {
    id: 187,
    phoneCode: 590,
    countryCode: "BL",
    countryNameEn: "Saint Barthelemy",
    alpha_3: "BLM",
    continentCode: "NA",
    continentNameEn: "North America",
  },
  {
    id: 188,
    phoneCode: 290,
    countryCode: "SH",
    countryNameEn: "Saint Helena",
    alpha_3: "SHN",
    continentCode: "AF",
    continentNameEn: "Africa",
  },
  {
    id: 189,
    phoneCode: 1869,
    countryCode: "KN",
    countryNameEn: "Saint Kitts and Nevis",
    alpha_3: "KNA",
    continentCode: "NA",
    continentNameEn: "North America",
  },
  {
    id: 190,
    phoneCode: 1758,
    countryCode: "LC",
    countryNameEn: "Saint Lucia",
    alpha_3: "LCA",
    continentCode: "NA",
    continentNameEn: "North America",
  },
  {
    id: 191,
    phoneCode: 590,
    countryCode: "MF",
    countryNameEn: "Saint Martin",
    alpha_3: "MAF",
    continentCode: "NA",
    continentNameEn: "North America",
  },
  {
    id: 192,
    phoneCode: 508,
    countryCode: "PM",
    countryNameEn: "Saint Pierre and Miquelon",
    alpha_3: "SPM",
    continentCode: "NA",
    continentNameEn: "North America",
  },
  {
    id: 193,
    phoneCode: 1784,
    countryCode: "VC",
    countryNameEn: "Saint Vincent and the Grenadines",
    alpha_3: "VCT",
    continentCode: "NA",
    continentNameEn: "North America",
  },
  {
    id: 194,
    phoneCode: 684,
    countryCode: "WS",
    countryNameEn: "Samoa",
    alpha_3: "WSM",
    continentCode: "OC",
    continentNameEn: "Oceania",
  },
  {
    id: 195,
    phoneCode: 378,
    countryCode: "SM",
    countryNameEn: "San Marino",
    alpha_3: "SMR",
    continentCode: "EU",
    continentNameEn: "Europe",
  },
  {
    id: 196,
    phoneCode: 239,
    countryCode: "ST",
    countryNameEn: "Sao Tome and Principe",
    alpha_3: "STP",
    continentCode: "AF",
    continentNameEn: "Africa",
  },
  {
    id: 197,
    phoneCode: 966,
    countryCode: "SA",
    countryNameEn: "Saudi Arabia",
    alpha_3: "SAU",
    continentCode: "AS",
    continentNameEn: "Asia",
  },
  {
    id: 198,
    phoneCode: 221,
    countryCode: "SN",
    countryNameEn: "Senegal",
    alpha_3: "SEN",
    continentCode: "AF",
    continentNameEn: "Africa",
  },
  {
    id: 199,
    phoneCode: 381,
    countryCode: "RS",
    countryNameEn: "Serbia",
    alpha_3: "SRB",
    continentCode: "EU",
    continentNameEn: "Europe",
  },
  {
    id: 200,
    phoneCode: 381,
    countryCode: "CS",
    countryNameEn: "Serbia and Montenegro",
    alpha_3: "SCG",
    continentCode: "EU",
    continentNameEn: "Europe",
  },
  {
    id: 201,
    phoneCode: 248,
    countryCode: "SC",
    countryNameEn: "Seychelles",
    alpha_3: "SYC",
    continentCode: "AF",
    continentNameEn: "Africa",
  },
  {
    id: 202,
    phoneCode: 232,
    countryCode: "SL",
    countryNameEn: "Sierra Leone",
    alpha_3: "SLE",
    continentCode: "AF",
    continentNameEn: "Africa",
  },
  {
    id: 203,
    phoneCode: 65,
    countryCode: "SG",
    countryNameEn: "Singapore",
    alpha_3: "SGP",
    continentCode: "AS",
    continentNameEn: "Asia",
  },
  {
    id: 204,
    phoneCode: 1,
    countryCode: "SX",
    countryNameEn: "Sint Maarten",
    alpha_3: "SXM",
    continentCode: "NA",
    continentNameEn: "North America",
  },
  {
    id: 205,
    phoneCode: 421,
    countryCode: "SK",
    countryNameEn: "Slovakia",
    alpha_3: "SVK",
    continentCode: "EU",
    continentNameEn: "Europe",
  },
  {
    id: 206,
    phoneCode: 386,
    countryCode: "SI",
    countryNameEn: "Slovenia",
    alpha_3: "SVN",
    continentCode: "EU",
    continentNameEn: "Europe",
  },
  {
    id: 207,
    phoneCode: 677,
    countryCode: "SB",
    countryNameEn: "Solomon Islands",
    alpha_3: "SLB",
    continentCode: "OC",
    continentNameEn: "Oceania",
  },
  {
    id: 208,
    phoneCode: 252,
    countryCode: "SO",
    countryNameEn: "Somalia",
    alpha_3: "SOM",
    continentCode: "AF",
    continentNameEn: "Africa",
  },
  {
    id: 209,
    phoneCode: 27,
    countryCode: "ZA",
    countryNameEn: "South Africa",
    alpha_3: "ZAF",
    continentCode: "AF",
    continentNameEn: "Africa",
  },
  {
    id: 210,
    phoneCode: 500,
    countryCode: "GS",
    countryNameEn: "South Georgia and the South Sandwich Islands",
    alpha_3: "SGS",
    continentCode: "AN",
    continentNameEn: "Antarctica",
  },
  {
    id: 211,
    phoneCode: 211,
    countryCode: "SS",
    countryNameEn: "South Sudan",
    alpha_3: "SSD",
    continentCode: "AF",
    continentNameEn: "Africa",
  },
  {
    id: 212,
    phoneCode: 34,
    countryCode: "ES",
    countryNameEn: "Spain",
    countryNameDe: "Spanien",
    alpha_3: "ESP",
    continentCode: "EU",
    continentNameEn: "Europe",
  },
  {
    id: 213,
    phoneCode: 94,
    countryCode: "LK",
    countryNameEn: "Sri Lanka",
    alpha_3: "LKA",
    continentCode: "AS",
    continentNameEn: "Asia",
  },
  {
    id: 214,
    phoneCode: 249,
    countryCode: "SD",
    countryNameEn: "Sudan",
    alpha_3: "SDN",
    continentCode: "AF",
    continentNameEn: "Africa",
  },
  {
    id: 215,
    phoneCode: 597,
    countryCode: "SR",
    countryNameEn: "Suriname",
    alpha_3: "SUR",
    continentCode: "SA",
    continentNameEn: "South America",
  },
  {
    id: 216,
    phoneCode: 47,
    countryCode: "SJ",
    countryNameEn: "Svalbard and Jan Mayen",
    alpha_3: "SJM",
    continentCode: "EU",
    continentNameEn: "Europe",
  },
  {
    id: 217,
    phoneCode: 268,
    countryCode: "SZ",
    countryNameEn: "Swaziland",
    alpha_3: "SWZ",
    continentCode: "AF",
    continentNameEn: "Africa",
  },
  {
    id: 218,
    phoneCode: 46,
    countryCode: "SE",
    countryNameEn: "Sweden",
    alpha_3: "SWE",
    continentCode: "EU",
    continentNameEn: "Europe",
  },
  {
    id: 219,
    phoneCode: 41,
    countryCode: "CH",
    countryNameEn: "Switzerland",
    countryNameDe: "Schweiz",
    alpha_3: "CHE",
    continentCode: "EU",
    continentNameEn: "Europe",
  },
  {
    id: 220,
    phoneCode: 963,
    countryCode: "SY",
    countryNameEn: "Syrian Arab Republic",
    alpha_3: "SYR",
    continentCode: "AS",
    continentNameEn: "Asia",
  },
  {
    id: 221,
    phoneCode: 886,
    countryCode: "TW",
    countryNameEn: "Taiwan, Province of China",
    alpha_3: "TWN",
    continentCode: "AS",
    continentNameEn: "Asia",
  },
  {
    id: 222,
    phoneCode: 992,
    countryCode: "TJ",
    countryNameEn: "Tajikistan",
    alpha_3: "TJK",
    continentCode: "AS",
    continentNameEn: "Asia",
  },
  {
    id: 223,
    phoneCode: 255,
    countryCode: "TZ",
    countryNameEn: "Tanzania, United Republic of",
    alpha_3: "TZA",
    continentCode: "AF",
    continentNameEn: "Africa",
  },
  {
    id: 224,
    phoneCode: 66,
    countryCode: "TH",
    countryNameEn: "Thailand",
    alpha_3: "THA",
    continentCode: "AS",
    continentNameEn: "Asia",
  },
  {
    id: 225,
    phoneCode: 670,
    countryCode: "TL",
    countryNameEn: "Timor-Leste",
    alpha_3: "TLS",
    continentCode: "AS",
    continentNameEn: "Asia",
  },
  {
    id: 226,
    phoneCode: 228,
    countryCode: "TG",
    countryNameEn: "Togo",
    alpha_3: "TGO",
    continentCode: "AF",
    continentNameEn: "Africa",
  },
  {
    id: 227,
    phoneCode: 690,
    countryCode: "TK",
    countryNameEn: "Tokelau",
    alpha_3: "TKL",
    continentCode: "OC",
    continentNameEn: "Oceania",
  },
  {
    id: 228,
    phoneCode: 676,
    countryCode: "TO",
    countryNameEn: "Tonga",
    alpha_3: "TON",
    continentCode: "OC",
    continentNameEn: "Oceania",
  },
  {
    id: 229,
    phoneCode: 1868,
    countryCode: "TT",
    countryNameEn: "Trinidad and Tobago",
    alpha_3: "TTO",
    continentCode: "NA",
    continentNameEn: "North America",
  },
  {
    id: 230,
    phoneCode: 216,
    countryCode: "TN",
    countryNameEn: "Tunisia",
    alpha_3: "TUN",
    continentCode: "AF",
    continentNameEn: "Africa",
  },
  {
    id: 231,
    phoneCode: 90,
    countryCode: "TR",
    countryNameEn: "Turkey",
    alpha_3: "TUR",
    continentCode: "AS",
    continentNameEn: "Asia",
  },
  {
    id: 232,
    phoneCode: 7370,
    countryCode: "TM",
    countryNameEn: "Turkmenistan",
    alpha_3: "TKM",
    continentCode: "AS",
    continentNameEn: "Asia",
  },
  {
    id: 233,
    phoneCode: 1649,
    countryCode: "TC",
    countryNameEn: "Turks and Caicos Islands",
    alpha_3: "TCA",
    continentCode: "NA",
    continentNameEn: "North America",
  },
  {
    id: 234,
    phoneCode: 688,
    countryCode: "TV",
    countryNameEn: "Tuvalu",
    alpha_3: "TUV",
    continentCode: "OC",
    continentNameEn: "Oceania",
  },
  {
    id: 235,
    phoneCode: 256,
    countryCode: "UG",
    countryNameEn: "Uganda",
    alpha_3: "UGA",
    continentCode: "AF",
    continentNameEn: "Africa",
  },
  {
    id: 236,
    phoneCode: 380,
    countryCode: "UA",
    countryNameEn: "Ukraine",
    alpha_3: "UKR",
    continentCode: "EU",
    continentNameEn: "Europe",
  },
  {
    id: 237,
    phoneCode: 971,
    countryCode: "AE",
    countryNameEn: "United Arab Emirates",
    alpha_3: "ARE",
    continentCode: "AS",
    continentNameEn: "Asia",
  },
  {
    id: 238,
    phoneCode: 44,
    countryCode: "GB",
    countryNameEn: "United Kingdom",
    alpha_3: "GBR",
    continentCode: "EU",
    continentNameEn: "Europe",
  },
  {
    id: 239,
    phoneCode: 1,
    countryCode: "US",
    countryNameEn: "United States",
    alpha_3: "USA",
    continentCode: "NA",
    continentNameEn: "North America",
  },
  {
    id: 240,
    phoneCode: 1,
    countryCode: "UM",
    countryNameEn: "United States Minor Outlying Islands",
    alpha_3: "UMI",
    continentCode: "NA",
    continentNameEn: "North America",
  },
  {
    id: 241,
    phoneCode: 598,
    countryCode: "UY",
    countryNameEn: "Uruguay",
    alpha_3: "URY",
    continentCode: "SA",
    continentNameEn: "South America",
  },
  {
    id: 242,
    phoneCode: 998,
    countryCode: "UZ",
    countryNameEn: "Uzbekistan",
    alpha_3: "UZB",
    continentCode: "AS",
    continentNameEn: "Asia",
  },
  {
    id: 243,
    phoneCode: 678,
    countryCode: "VU",
    countryNameEn: "Vanuatu",
    alpha_3: "VUT",
    continentCode: "OC",
    continentNameEn: "Oceania",
  },
  {
    id: 244,
    phoneCode: 58,
    countryCode: "VE",
    countryNameEn: "Venezuela",
    alpha_3: "VEN",
    continentCode: "SA",
    continentNameEn: "South America",
  },
  {
    id: 245,
    phoneCode: 84,
    countryCode: "VN",
    countryNameEn: "Viet Nam",
    alpha_3: "VNM",
    continentCode: "AS",
    continentNameEn: "Asia",
  },
  {
    id: 246,
    phoneCode: 1284,
    countryCode: "VG",
    countryNameEn: "Virgin Islands, British",
    alpha_3: "VGB",
    continentCode: "NA",
    continentNameEn: "North America",
  },
  {
    id: 247,
    phoneCode: 1340,
    countryCode: "VI",
    countryNameEn: "Virgin Islands, U.s.",
    alpha_3: "VIR",
    continentCode: "NA",
    continentNameEn: "North America",
  },
  {
    id: 248,
    phoneCode: 681,
    countryCode: "WF",
    countryNameEn: "Wallis and Futuna",
    alpha_3: "WLF",
    continentCode: "OC",
    continentNameEn: "Oceania",
  },
  {
    id: 249,
    phoneCode: 212,
    countryCode: "EH",
    countryNameEn: "Western Sahara",
    alpha_3: "ESH",
    continentCode: "AF",
    continentNameEn: "Africa",
  },
  {
    id: 250,
    phoneCode: 967,
    countryCode: "YE",
    countryNameEn: "Yemen",
    alpha_3: "YEM",
    continentCode: "AS",
    continentNameEn: "Asia",
  },
  {
    id: 251,
    phoneCode: 260,
    countryCode: "ZM",
    countryNameEn: "Zambia",
    alpha_3: "ZMB",
    continentCode: "AF",
    continentNameEn: "Africa",
  },
  {
    id: 252,
    phoneCode: 263,
    countryCode: "ZW",
    countryNameEn: "Zimbabwe",
    alpha_3: "ZWE",
    continentCode: "AF",
    continentNameEn: "Africa",
  },
];