export const SPORTEVENTS_LOADING = "SPORTEVENTS_LOADING";
export const SPORTEVENTS_FAILED = "SPORTEVENTS_FAILED";
export const ADD_SPORTEVENTS = "ADD_SPORTEVENTS";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";

export const SPORTS_LOADING = "SPORTS_LOADING";
export const SPORTS_FAILED = "SPORTS_FAILED";
export const ADD_SPORTS = "ADD_SPORTS";
